-- MySQL Script generated by MySQL Workbench
-- 03/23/19 08:34:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`leader_club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leader_club` (
  `idleader` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `class` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idleader`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idsa` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `class` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`idsa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `idleader` INT NOT NULL,
  `idsa` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_leader_club_idx` (`idleader` ASC),
  INDEX `fk_user_sa1_idx` (`idsa` ASC),
  CONSTRAINT `fk_user_leader_club`
    FOREIGN KEY (`idleader`)
    REFERENCES `mydb`.`leader_club` (`idleader`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_sa1`
    FOREIGN KEY (`idsa`)
    REFERENCES `mydb`.`admin` (`idsa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`club` (
  `idclub` INT NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `member` INT NULL,
  `leader_club_idleader` INT NOT NULL,
  `sa_idsa` INT NOT NULL,
  PRIMARY KEY (`idclub`),
  INDEX `fk_club_leader_club1_idx` (`leader_club_idleader` ASC),
  INDEX `fk_club_sa1_idx` (`sa_idsa` ASC),
  CONSTRAINT `fk_club_leader_club1`
    FOREIGN KEY (`leader_club_idleader`)
    REFERENCES `mydb`.`leader_club` (`idleader`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_club_sa1`
    FOREIGN KEY (`sa_idsa`)
    REFERENCES `mydb`.`admin` (`idsa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`file_report` (
  `idfile` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `sa_idsa` INT NOT NULL,
  `leader_club_idleader` INT NOT NULL,
  PRIMARY KEY (`idfile`),
  INDEX `fk_file_report_sa1_idx` (`sa_idsa` ASC),
  INDEX `fk_file_report_leader_club1_idx` (`leader_club_idleader` ASC),
  CONSTRAINT `fk_file_report_sa1`
    FOREIGN KEY (`sa_idsa`)
    REFERENCES `mydb`.`admin` (`idsa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_report_leader_club1`
    FOREIGN KEY (`leader_club_idleader`)
    REFERENCES `mydb`.`leader_club` (`idleader`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_club` (
  `idmember` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `class` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `club_idclub` INT NOT NULL,
  PRIMARY KEY (`idmember`),
  INDEX `fk_member_club_club1_idx` (`club_idclub` ASC),
  CONSTRAINT `fk_member_club_club1`
    FOREIGN KEY (`club_idclub`)
    REFERENCES `mydb`.`club` (`idclub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
